stages:
  data_ingestion:
    cmd: python src/chondrosarcomas_detection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/chondrosarcomas_detection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  
  prepare_base_model:
    cmd: python src/chondrosarcomas_detection/pipeline/stage_02_base_model.py
    deps:
      - src/chondrosarcomas_detection/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model_model


  training:
    cmd: python src/chondrosarcomas_detection/pipeline/stage_03_model_trainer.py
    deps:
      - src/chondrosarcomas_detection/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_base_model_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/chondrosarcomas_detection/pipeline/stage_04_model_evaluation_mlflow.py
    deps:
      - src/chondrosarcomas_detection/pipeline/stage_04_model_evaluation_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false

